# Generated by Django 3.0.3 on 2020-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('cus_gmail_id', models.CharField(max_length=50)),
                ('plan_duration', models.CharField(max_length=10)),
            ],
        ),
    ]
