# Generated by Django 3.0.3 on 2020-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cus_gmail_id',
            field=models.CharField(max_length=20),
        ),
    ]
