# Generated by Django 3.0.3 on 2020-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=50)),
                ('offer_description', models.CharField(max_length=50)),
                ('offer_cost', models.CharField(max_length=150)),
                ('offer_duration', models.CharField(max_length=50)),
                ('offer_discount', models.CharField(max_length=50)),
                ('bank_offers', models.CharField(max_length=250)),
            ],
        ),
    ]
