# Generated by Django 3.0.3 on 2020-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('ph_no', models.CharField(max_length=35)),
                ('gmail', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
