# Generated by Django 3.0.3 on 2020-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='key',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
